services:
  keycloakdb:
    image: postgres
    container_name: keycloakdb
    restart: unless-stopped
    volumes:
      - ./keycloak/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kcdb
      POSTGRES_USER: kcadmin
      POSTGRES_PASSWORD_FILE: /run/secrets/pgpwd
    secrets:
      - pgpwd
  keycloak:
    image: hieupth/keywind
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - keycloakdb
    command: start
    ports:
      - 8080:8080
    environment:
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/kcdb
      KC_DB_USERNAME: kcadmin
      KC_DB_PASSWORD_FILE: /run/secrets/pgpwd
    secrets:
      - pgpwd

secrets:
  pgpwd:
    file: secrets/pgpwd.txt